# Generated by Django 2.2.3 on 2022-05-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicos',
            new_name='Servico',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='modificados',
            new_name='modificado',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='modificados',
            new_name='modificado',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='modificados',
            new_name='modificado',
        ),
    ]
